#!/bin/bash
if test $1 -gt 0 ; then num=$1 ; else num=4 ; fi
echo "Start ${num} test processes"
tempfile="temphosts"
for i in $(seq 1 ${num}) ; do
    ( echo "${i} localhost $((1023+i))" >> "${tempfile}" )
done
for i in $(seq 1 ${num}) ; do
	( python main.py -h ${tempfile} -p $((1023+i)) & )
done
sleep 5
rm ${tempfile}
