#!/bin/bash
echo "Start 4 test processes"
tempfile="temphosts"
cat >${tempfile} <<CFG
1 localhost 1024
2 localhost 1025
3 localhost 1026
4 localhost 1027
CFG
for i in {1..4} ; do
	( python main.py -h ${tempfile} -p $((1023+i)) & )
done
sleep 6
rm ${tempfile}